site_name: Mass Spec Coronavirus Public Data
edit_uri: https://github.com/mwang87/MassSpec-Coronavirus-Project-Docs/blob/master/docs/
nav:
    - Introduction: index.md
    - Metabolomics: metabolomics.md
    - Proteomics: proteomics.md
theme:
    name: material
plugins:
    - search
    - git-revision-date
google_analytics: ['UA-8412213-10', 'mwang87.github.io']
